services:
  kraken-sandbox:
    container_name: kraken-sandbox
    build: .
    ports:
      - "5555:5555"
    volumes:
      - ./data:/app/data
      - .:/app
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
        reservations:
          cpus: 0.1
          memory: 128M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - kraken_network

networks:
  kraken_network:
    driver: bridge
    external: true # create this network first: docker network create kraken_network